### ISSUE TITLE
gpu error

### ISSUE THREAD

**Issue by MinkyuHa** [Hanjun-Dai/sdvae#3]
Dear Hanjun Dai
Thanks for your sdvae implementation in github in advance.
Let me ask you one question about error while gpu running in run_train.sh .

I'm running the code on cuda8.0 + python 2.7 + pytorch 0.3.1
When I execute the run_train.sh, it shows this error on ae.cuda()
However when I change the mode from gpu to cpu, it works fine.

Could you check this behavior of gpu?

best regards, Minkyu Ha

--------
<error log>

Namespace(ae_type='vae', batch_size=300, bondcompact=0, data_dump='../../dropbox/data/zinc/250k_rndm_zinc_drugs_clean.h5', data_gen_threads=None, encoder_type='cnn', eps_std=0.01, grammar_file='../../dropbox/context_free_grammars/mol_zinc.grammar', kl_coeff=1.0, latent_dim=56, learning_rate=0.0001, loss_type='vanilla', max_decode_steps=278, mode='gpu', num_epochs=500, prob_fix=0.0, rnn_type='gru', save_dir='/home/minkyuha/scratch/results/graph_generation/vanilla-sk-0-mol_vae/enc-cnn-loss-vanilla-eps-0.01-rnn-gru-kl-1', saved_model=None, seed=1, skip_deter=0, smiles_file=None)
using vae
a Conv1d inited
a Conv1d inited
a Conv1d inited
a Linear inited
a Linear inited
a Linear inited
a Linear inited
a GRU inited
a Linear inited
Traceback (most recent call last):
  File "train_zinc.py", line 162, in <module>
    main()
  File "train_zinc.py", line 124, in main
    **ae = ae.cuda()**
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/minkyuha/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError
 > /home/minkyuha/anaconda2/lib/python2.7/site- packages/torch/backends/cudnn/rnn.py(165)get_parameters()
 -> assert filter_dim_a.prod() == filter_dim_a[0]

**Comment by MinkyuHa** [comment]
Hello, 

I fixed it from my side.
I upgraded the pytorch to the latest version 0.4.1.
and fixed the error & warning message in train_zinc.py.
.cpu().numpy()[0] ==> .cpu().numpy()    # remove index.

It works fine.

Thank you.
